### ISSUE TITLE
Properly deleting input garbage

### ISSUE THREAD

**Issue by marcosmarp** [marcosmarp/bookshop#5]
Working on #4, i stumbled across the fact that the input stream gets filled with residous user ingresed characters; the main example of this is the '/n' used to finish a line.

What i'm using right now to "clean" the input is this: 
>std::cin.clear();
std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');

That seems to work fine for numeric inputs, like asking the user to select a choice between 1, 2 or 3. But the moment i start to ask the user for string-type inputs, things dont work like they should. To give you an example:

![image](https://user-images.githubusercontent.com/88422056/128642201-7e07e81d-69ce-48b3-a4e8-08f1080207f0.png)

Between the author and the publish, i had to press the Enter key twice. And between the publisher and the price, everything went nuts, to get to the price entering section i had to enter a number for some reason.

I suspect that this is caused in this specific part of the code cause i'm asking the user to enter a number just after entering a string. Take a look: 

    printTab(1);
    std::cout << "Title: ";
    wipeInput();
    std::getline(std::cin, book[bookPosition].name);
    std::cout << std::endl;

    printTab(1);
    std::cout << "Author: ";
    wipeInput();
    std::getline(std::cin, book[bookPosition].author);
    std::cout << std::endl;

    printTab(1);
    std::cout << "Publisher: ";
    wipeInput();
    std::getline(std::cin, book[bookPosition].publisher);
    std::cout << std::endl;

    printTab(1);
    book[bookPosition].releaseDate = receiveNumericInput();
    std::cout << std::endl;

    printTab(1);
    std::cout << "Price: ";
    book[bookPosition].price = receiveNumericInput();
    std::cout << std::endl;

    printTab(1);
    std::cout << "Amount of copies: ";
    book[bookPosition].stockAmount = receiveNumericInput();
    std::cout << std::endl << std::endl;

**Comment by nahueespinosa** [comment]
Yeah, there are a couple of issues here. This may help you: http://www.math.uaa.alaska.edu/~afkjm/csce211/handouts/ReadingLineOfText.pdf

You can also debug and see what's happening exactly with this technique:
```
void wipeInput() {
  std::cout << "(Wiping)";
  ...
  std::cout << "(Wiped)";
}
```

**Comment by marcosmarp** [comment]
Okay, i think i got it. I'll update the PR and ask for your review there. Thanks!
